### ISSUE TITLE
Incorrect keymap size

### ISSUE THREAD

**Issue by chrisduerr** [jjsullivan5196/wvkbd#35]
I'm not entirely sure if this is technically *incorrect*, but I've encountered issues trying to start wvkbd on my own compositor and XKB is throwing errors that the keymap isn't valid. Looking into it, I noticed that wvkbd seems to be uploading a keymap with 55 trailing `\0` bytes.

Looking at the wvkbd code, you seem to be adding `64` to the length of the keymap:
https://github.com/jjsullivan5196/wvkbd/blob/9bbc8d4a990f8af345b2f4638d201252d34b27dd/keyboard.c#L518

That's 10 more than I would have expected, but still seems like it might be related to the issue. Is there a reason why you're sending a keymap with a bigger size than the underlying keymap actually is? Allocating more memory and putting garbage in the FD pointed to doesn't really matter, but reporting an incorrect size in the keymap request would seem a bit strange to me.

**Comment by proycon** [comment]
This indeed seems rather odd, I'm not sure at all anymore where the 64 came from, despite being the person who added it in the first place apparently. This may need some deeper investigation, I agree things would be cleaner if the keymap that goes into zwp_virtual_keyboard_v1_keymap() does not have a whole bunch of trailing 0 bytes.

**Comment by proycon** [comment]
I checked the code and remember now why the added buffer. For some keys that are not in the keymap, we dynamically inject the code into the keymap temporarily, i.e. we change the keymap on the fly so keys can be pressed that were not in the original keymap can be used. One dummy key in the keymap is reserved to hold those values. The +64 is maybe a bit arbitrary but is so that it fits in memory even for the largest unicode codes.

That being said, we should pass the right size. I submitted a patch for review, should be merged soon: https://lists.sr.ht/~mil/sxmo-devel/patches/40815

**Comment by anjandev** [comment]
Hey @proycon, I have merged in your patch. Nice change and good catch. A couple of follow up action items. It seems I dont have permissions to the github repo. Can you please:

1. close this issue
2. push the wvkbd on sourcehut git repo to the wvkbd github git repo

Thank you @chrisduerr for reporting the issue.

**Comment by realroot2185** [comment]
https://github.com/Smithay/smithay/issues/1355
Is this a wvkbd bug?

**Comment by proycon** [comment]
@realroot2185 See #70, I think it's an issue in smithay (or underlying dependencies), it doesn't reproduce on any other  compositor thus-far

**Comment by proycon** [comment]
Unless there are indeed this trailing \0 bytes and this issue wasn't fixed properly..
